image: jelaniwoods/appdev2021-vanilla-rails-hotfix

tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - vortizhe.simple-ruby-erb
    - CraigMaslowski.erb
    - Vense.rails-snippets
    - wingrunr21.vscode-ruby
